[build-system]

requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools]
py-modules = ["xrayreco"]

[project]
name = "xrayreco"
version = "0.1"
dependencies = [
    "sphinxawesome_theme"
]